# Generated by Django 4.2.7 on 2025-10-25 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الكاميرا")),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            ("simulation", "كاميرا محاكاة"),
                            ("real", "كاميرا حقيقية"),
                        ],
                        default="simulation",
                        max_length=20,
                        verbose_name="نوع الكاميرا",
                    ),
                ),
                (
                    "location_lat",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "location_lng",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_cameras",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "كاميرا",
                "verbose_name_plural": "الكاميرات",
                "db_table": "surveillance_cameras",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="التاريخ")),
                (
                    "total_media_processed",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الوسائط المعالجة"
                    ),
                ),
                (
                    "successful_processing",
                    models.IntegerField(default=0, verbose_name="المعالجات الناجحة"),
                ),
                (
                    "failed_processing",
                    models.IntegerField(default=0, verbose_name="المعالجات الفاشلة"),
                ),
                (
                    "total_alerts_generated",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الإنذارات المولدة"
                    ),
                ),
                (
                    "avg_processing_time",
                    models.FloatField(
                        default=0.0, verbose_name="متوسط وقت المعالجة (ثانية)"
                    ),
                ),
            ],
            options={
                "verbose_name": "إحصائية معالجة",
                "verbose_name_plural": "إحصائيات المعالجة",
                "db_table": "surveillance_processing_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.JSONField(verbose_name="القيمة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "db_table": "surveillance_system_settings",
            },
        ),
        migrations.CreateModel(
            name="ThreatAssessmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الكائن"
                    ),
                ),
                (
                    "base_risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "حرج"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        max_length=20,
                        verbose_name="مستوى الخطورة الأساسي",
                    ),
                ),
                (
                    "confidence_threshold_high",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="حد الثقة للخطورة العالية",
                    ),
                ),
                (
                    "confidence_threshold_medium",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="حد الثقة للخطورة المتوسطة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تكوين تقييم التهديد",
                "verbose_name_plural": "تكوينات تقييم التهديدات",
                "db_table": "threat_assessment_config",
                "ordering": ["object_name"],
            },
        ),
        migrations.CreateModel(
            name="ThreatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نوع التهديد")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "حرج"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="مستوى الخطورة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "detection_count",
                    models.IntegerField(default=0, verbose_name="عدد مرات الكشف"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "نوع التهديد",
                "verbose_name_plural": "أنواع التهديدات",
                "db_table": "surveillance_threat_types",
                "ordering": ["-risk_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "صورة"), ("video", "فيديو")],
                        max_length=10,
                        verbose_name="نوع الوسائط",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="surveillance/media/%Y/%m/%d/", verbose_name="الملف"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="حجم الملف (بايت)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="تم المعالجة"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="خطأ المعالجة"),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بدء المعالجة"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انتهاء المعالجة"
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="surveillance.camera",
                        verbose_name="الكاميرا",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف وسائط",
                "verbose_name_plural": "ملفات الوسائط",
                "db_table": "surveillance_media_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="درجة الحرارة (°C)")),
                (
                    "humidity",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="الرطوبة (%)",
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="سرعة الرياح (كم/س)",
                    ),
                ),
                (
                    "visibility",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="مدى الرؤية (كم)",
                    ),
                ),
                (
                    "weather_condition",
                    models.CharField(max_length=100, verbose_name="حالة الطقس"),
                ),
                (
                    "pressure",
                    models.FloatField(
                        blank=True, null=True, verbose_name="الضغط الجوي (hPa)"
                    ),
                ),
                (
                    "precipitation",
                    models.FloatField(default=0.0, verbose_name="هطول الأمطار (مم)"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="openweathermap",
                        max_length=50,
                        verbose_name="مصدر البيانات",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="surveillance.camera",
                        verbose_name="الكاميرا",
                    ),
                ),
            ],
            options={
                "verbose_name": "بيانات الطقس",
                "verbose_name_plural": "بيانات الطقس",
                "db_table": "surveillance_weather_data",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["camera", "recorded_at"],
                        name="surveillanc_camera__c58724_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "حرج"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        max_length=20,
                        verbose_name="مستوى الخطورة",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="نسبة الثقة في الكشف (من 0 إلى 1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="مستوى الثقة",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف التهديد"),
                ),
                (
                    "location_lat",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "location_lng",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "detected_objects",
                    models.JSONField(
                        default=dict,
                        help_text="تفاصيل الكائنات المكتشفة بتنسيق JSON",
                        verbose_name="الكائنات المكتشفة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("under_review", "تحت المراجعة"),
                            ("resolved", "تم المعالجة"),
                            ("false_alarm", "إنذار كاذب"),
                            ("ignored", "تم التجاهل"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المراجعة"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="surveillance.mediafile",
                        verbose_name="ملف الوسائط",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم المراجعة بواسطة",
                    ),
                ),
                (
                    "threat_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="surveillance.threattype",
                        verbose_name="نوع التهديد",
                    ),
                ),
            ],
            options={
                "verbose_name": "إنذار",
                "verbose_name_plural": "الإنذارات",
                "db_table": "surveillance_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "risk_level"],
                        name="surveillanc_status_d5c143_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="surveillanc_created_fd2f1f_idx"
                    ),
                    models.Index(
                        fields=["threat_type", "risk_level"],
                        name="surveillanc_threat__6bc94c_idx",
                    ),
                ],
            },
        ),
    ]
