# Generated by Django 4.2.7 on 2025-10-25 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishermanReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان البلاغ"),
                ),
                ("description", models.TextField(verbose_name="وصف البلاغ")),
                (
                    "location_lat",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "location_lng",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "حرج"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="مستوى الخطورة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("verified", "تم التحقق"),
                            ("rejected", "مرفوض"),
                            ("resolved", "تم الحل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة البلاغ",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fisherman",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "fisherman"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fisherman_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الصياد",
                    ),
                ),
                (
                    "media_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fisherman_reports",
                        to="surveillance.mediafile",
                        verbose_name="الوسائط المرفقة",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الحل بواسطة",
                    ),
                ),
                (
                    "threat_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveillance.threattype",
                        verbose_name="نوع التهديد",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاغ صياد",
                "verbose_name_plural": "بلاغات الصيادين",
                "db_table": "fisherman_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
