# Generated by Django 5.2.8 on 2025-12-28 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_fishermanreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishermanreport',
            options={},
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='fisherman',
            field=models.ForeignKey(limit_choices_to={'user_type': 'fisherman'}, on_delete=django.db.models.deletion.CASCADE, related_name='fisherman_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='fisherman_reports', to='surveillance.mediafile'),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='risk_level',
            field=models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض'), ('resolved', 'تم الحل')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='threat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance.threattype'),
        ),
        migrations.AlterField(
            model_name='fishermanreport',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='fishermanreport',
            table=None,
        ),
    ]
