# Generated by Django 5.2.8 on 2025-12-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_alter_fishermanreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='surveillance.camera'),
        ),
    ]
