# Generated by Django 5.2.8 on 2026-02-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveillance", "0004_alter_mediafile_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="weather_main",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="الحالة العامة للطقس"
            ),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_degree",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="اتجاه الرياح (درجة)"
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_data",
                to="surveillance.camera",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="data_source",
            field=models.CharField(default="openweathermap", max_length=50),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(default=0.0, verbose_name="الهطول (مم)"),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="weather_condition",
            field=models.CharField(max_length=100, verbose_name="وصف حالة الطقس"),
        ),
    ]
