# Generated by Django 5.2.8 on 2026-02-22 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "surveillance",
            "0005_weatherdata_weather_main_weatherdata_wind_degree_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="alert",
            name="surveillanc_threat__6bc94c_idx",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="description",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="location_lat",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="location_lng",
        ),
        migrations.AddField(
            model_name="alert",
            name="ai_decision",
            field=models.CharField(
                blank=True,
                help_text="AI decision (e.g. Human review required)",
                max_length=100,
                verbose_name="قرار الذكاء الاصطناعي",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="ai_explanation",
            field=models.TextField(
                blank=True,
                help_text="Human-readable AI explanation",
                verbose_name="تفسير الذكاء الاصطناعي",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="ai_raw_output",
            field=models.JSONField(
                blank=True,
                help_text="Raw detection output from YOLO model",
                null=True,
                verbose_name="AI Raw Output",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="confidence",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="مستوى الثقة",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="detected_objects",
            field=models.JSONField(
                default=dict,
                help_text="Interpreted detected objects",
                verbose_name="الكائنات المكتشفة (مفسّرة)",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تمت المراجعة بواسطة",
            ),
        ),
    ]
