# Generated by Django 5.2.8 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveillance", "0006_alter_alert_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="advanced_analysis",
            field=models.TextField(
                blank=True,
                help_text="Full contextual AI analysis",
                verbose_name="Advanced AI Analysis",
            ),
        ),
    ]
